(()=>{const c=document.querySelector('#game'),x=c.getContext('2d'),W=c.width,H=c.height,keys=new Set();let state='ready',score=0,lives=3,wave=10,player,bullets=[],enemies=[],blocks=[],fx=[],last=0,sound=true,audio;
const rnd=(a,b)=>Math.random()*(b-a)+a, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function makeMap(){blocks=[];const w=34,h=24,lanes=[105,W/2,W-105];for(let row=0;row<5;row++)for(let lane=0;lane<3;lane++){const offset=(row%2?18:-18)*(lane===1?1:0);blocks.push({x:lanes[lane]-w/2+offset,y:70+row*72,w,h,steel:(row+lane)%7===0})}const cell=16,gap=4,ox=W/2-(5*cell+gap+5*cell)/2,oy=H/2-2.5*cell,Hp=['10001','10001','11111','10001','10001'],Dp=['11110','10001','10001','10001','11110'];[Hp,Dp].forEach((pat,l)=>pat.forEach((row,r)=>[...row].forEach((v,col)=>{if(v==='1')blocks.push({x:ox+col*cell+(l?5*cell+gap:0),y:oy+r*cell,w:cell-2,h:cell-2,initial:true})})))}
function reset(){score=0;lives=3;wave=10;bullets=[];enemies=[];fx=[];player={x:W/2,y:H-92,a:-Math.PI/2,r:14,cd:0,inv:0,hp:3,maxHp:3};makeMap();blocks=blocks.filter((q,i)=>!blocks.slice(0,i).some(p=>q.x<p.x+p.w&&q.x+q.w>p.x&&q.y<p.y+p.h&&q.y+q.h>p.y)&&Math.hypot(q.x+q.w/2-player.x,q.y+q.h/2-player.y)>24+Math.max(q.w,q.h)/2);for(let i=0;i<4;i++)spawn()}
function spawn(){if(wave<=0)return;wave--;let side=Math.floor(rnd(0,3));enemies.push({x:[35,W/2,W-35][side],y:32,a:Math.PI/2,r:14,cd:rnd(30,100),speed:rnd(.45,1),hp:2,maxHp:2,turn:rnd(20,80)})}
function hit(a,b){return Math.hypot(a.x-b.x,a.y-b.y)<(a.r||4)+(b.r||4)+6}
function shoot(t,owner){if(t.cd>0)return;t.cd=owner==='p'?15:rnd(55,100);bullets.push({x:t.x+Math.cos(t.a)*20,y:t.y+Math.sin(t.a)*20,a:t.a,owner,life:100,r:4});beep(180,owner==='p'?'.06':'.12')}
function beep(freq,dur){if(!sound)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+parseFloat(dur));o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+parseFloat(dur))}catch{}}
function overlaps(px,py,p,q){return px+p.r>q.x&&px-p.r<q.x+q.w&&py+p.r>q.y&&py-p.r<q.y+q.h}
function separateTanks(){const all=[player,...enemies.filter(e=>e.hp)];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const a=all[i],b=all[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r+5;if(d>0&&d<min){const push=(min-d)/2,ux=dx/d,uy=dy/d;a.x=clamp(a.x-ux*push,20,W-20);a.y=clamp(a.y-uy*push,35,H-28);b.x=clamp(b.x+ux*push,20,W-20);b.y=clamp(b.y+uy*push,35,H-28)}}}
function move(p,dx,dy){let nx=clamp(p.x+dx*p.speed,20,W-20),ny=clamp(p.y+dy*p.speed,35,H-28);const occupied=(tx,ty)=>blocks.some(q=>overlaps(tx,ty,p,q))||enemies.some(e=>e!==p&&e.hp&&Math.hypot(tx-e.x,ty-e.y)<p.r+e.r+5)||(p!==player&&Math.hypot(tx-player.x,ty-player.y)<p.r+player.r+5);let moved=false;if(!occupied(nx,p.y)){p.x=nx;moved=true}if(!occupied(p.x,ny)){p.y=ny;moved=true}return moved}
function update(dt){if(state!=='play')return;player.cd=Math.max(0,player.cd-dt);player.inv=Math.max(0,player.inv-dt);let dx=(keys.has('ArrowRight')||keys.has('d'))-(keys.has('ArrowLeft')||keys.has('a')),dy=(keys.has('ArrowDown')||keys.has('s'))-(keys.has('ArrowUp')||keys.has('w'));if(dx||dy){player.a=Math.atan2(dy,dx);player.speed=2.6;move(player,dx,dy)}if(keys.has(' ')||keys.has('j'))shoot(player,'p');enemies.forEach(e=>{e.cd-=dt;e.turn-=dt;if(e.turn<0){e.a+=rnd(-1.5,1.5);e.turn=rnd(30,90)}move(e,Math.cos(e.a),Math.sin(e.a));if(e.cd<0)shoot(e,'e')});bullets.forEach(b=>{b.x+=Math.cos(b.a)*5*dt;b.y+=Math.sin(b.a)*5*dt;b.life-=dt;blocks.forEach(q=>{if(b.x>q.x&&b.x<q.x+q.w&&b.y>q.y&&b.y<q.y+q.h)b.life=0});if(b.owner==='p')enemies.forEach(e=>{if(e.hp&&hit(b,e)){e.hp--;b.life=0;if(e.hp<=0){score+=40;burst(e.x,e.y)}else beep(110,'.08')}});else if(player.inv<=0&&hit(b,player)){b.life=0;player.hp--;player.inv=70;if(player.hp<=0){lives--;burst(player.x,player.y);if(lives<=0)end('GAME OVER');else{player.hp=player.maxHp;player.x=W/2;player.y=H-92}}};});bullets=bullets.filter(b=>b.life>0&&b.x>0&&b.x<W&&b.y>0&&b.y<H);enemies=enemies.filter(e=>e.hp>0);if(enemies.length<4&&wave>0)spawn();if(!wave&&!enemies.length)end('胜利！');fx.forEach(f=>{f.t-=dt;f.r+=dt*1.5});fx=fx.filter(f=>f.t>0)}
function burst(x0,y0){for(let i=0;i<14;i++)fx.push({x:x0,y:y0,r:2,t:25,vx:rnd(-2,2),vy:rnd(-2,2)}) ;beep(70,'.18')}
function drawTank(t,col){x.save();x.translate(t.x,t.y);x.rotate(t.a);x.fillStyle=col;x.fillRect(-t.r,-t.r,t.r*2,t.r*2);x.fillStyle='#0a161b';x.fillRect(-7,-7,14,14);x.fillStyle=col;x.fillRect(0,-3,t.r+9,6);x.restore();const bw=30,bh=4,ratio=Math.max(0,t.hp/t.maxHp);x.fillStyle='#071014';x.fillRect(t.x-bw/2,t.y-t.r-10,bw,bh);x.fillStyle=t===player?'#55d68b':'#ff665c';x.fillRect(t.x-bw/2,t.y-t.r-10,bw*ratio,bh)}
function draw(){x.clearRect(0,0,W,H);x.fillStyle='#10282a';x.fillRect(0,0,W,H);x.strokeStyle='#1b3c3b';for(let i=0;i<W;i+=32){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}for(let i=0;i<H;i+=32){x.beginPath();x.moveTo(0,i);x.lineTo(W,i);x.stroke()}blocks.forEach(q=>{x.fillStyle=q.base?'#b57b2b':q.steel?'#72868a':'#9b5234';x.fillRect(q.x,q.y,q.w,q.h);x.strokeStyle='#d89b51';x.strokeRect(q.x,q.y,q.w,q.h)});drawTank(player,'#e2a342');enemies.forEach(e=>drawTank(e,'#cc554b'));bullets.forEach(b=>{x.fillStyle=b.owner==='p'?'#ffe08a':'#ff7160';x.beginPath();x.arc(b.x,b.y,4,0,7);x.fill()});fx.forEach(f=>{x.fillStyle=`rgba(255,${80+f.t*4},30,${f.t/25})`;x.beginPath();x.arc(f.x,f.y,f.r,0,7);x.fill()})}
function end(title){state='end';document.querySelector('#overlay').hidden=false;document.querySelector('#overlay h2').textContent=title;document.querySelector('#overlay p').textContent=`最终分数 ${score} · 点击下方重新开始`;document.querySelector('#start').textContent='重新开始'}
function loop(t){let dt=Math.min(2,(t-last)/16.67||1);last=t;update(dt);draw();requestAnimationFrame(loop)}
document.addEventListener('keydown',e=>{keys.add(e.key);if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault()});document.addEventListener('keyup',e=>keys.delete(e.key));document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key==='Space'?' ':b.dataset.key;b.addEventListener('pointerdown',()=>keys.add(k));['pointerup','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});document.querySelector('#start').onclick=()=>{reset();state='play';document.querySelector('#overlay').hidden=true;beep(440,'.08')};document.querySelector('#pause').onclick=()=>{if(state==='play'){state='pause';document.querySelector('#pause').textContent='继续'}else if(state==='pause'){state='play';document.querySelector('#pause').textContent='暂停'}};document.querySelector('#sound').onclick=()=>{sound=!sound;document.querySelector('#sound').textContent=sound?'🔊 音效':'🔇 静音'};setInterval(()=>{document.querySelector('#score').textContent=score;document.querySelector('#lives').textContent=lives;document.querySelector('#remaining').textContent=wave+enemies.length},100);reset();requestAnimationFrame(loop)})();

